import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import "react-datepicker/dist/react-datepicker.css";
import "./datepicker-custom.css";
import { ToastProvider } from "@/context/ToastContext";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} font-sans antialiased text-[#2D3036]`}>
        <ToastProvider>
          {children}
        </ToastProvider>
      </body>
    </html>
  );
}
